name: IronGolemApperAndDie
version: '1.1-SNAPSHOT'
main: furycode.ironGolemApperAndDie.IronGolemApperAndDie
api-version: '1.21'
author: MatiasVME
description: "Causes golems to die 3 seconds after spawning with particles."
